title: "ihainan's Blog"
baseurl: ""

date_format: "%Y-%m-%d"

google_analytics: 'UA-41187412-2'
disqus_shortname: ihainan

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
