# Site wide configuration

title:            "ihainan's Blog"
locale:           en_US
url:              http://www.ihainan.me


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: ihainan
  avatar: bio-photo.jpg
  bio: "准研究生 & 准码农在北京，忙时饮茶，闲时酌酒。"
  email: "ihainan72@gmail.com"
  disqus-shortname: "ihainan"
  twitter: ihainan
  facebook: #username
  google:
    plus: ihainan
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: ihainan
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
